theme: minima
title: Portfolio
author: Krista Neth
email: kristaneth@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A portfolio including work and educational expirence. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
linkedin_username: Krista Neth
github_username:  axiompiper

show_excerpts: true # set to false to remove excerpts on the homepage


